### ISSUE TITLE
Webpack-cli version is outdated

### ISSUE THREAD

**Issue by barangerbenjamin** [lewagon/clearbit-livecode#1]
```"webpack-cli": "^2.1.2"``` is outdated and breaks the `yarn install`
Updgrading the version to ```"webpack-cli": "^3.1.1"``` fixes the issue.

I don't have the rights to make a PR on this repo 🙏

**Comment by ssaunier** [comment]
<img width="943" alt="image" src="https://user-images.githubusercontent.com/414418/101931174-5bdbb700-3bd9-11eb-8f76-108b1c782eff.png">

☝️ Possible now 🙈

**Comment by santiagosan93** [comment]
Thanks for the comment. 
I'm closing since the cli has been updated
